---
apiVersion: v1
kind: Secret
metadata:
  name: backend-apis-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-idp-demo/backend-apis-gitops